name: Custom Package

on:
  workflow_dispatch: 


permissions:
  packages: write      


concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event }}
  cancel-in-progress: true
jobs:
  windows:
    runs-on: windows-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install gpt-computer-assistant[agentic]
          pip install pyinstaller

        
      - name: Run PyInstaller with crewai included
        run: |
          # Use Python to find the 'crewai' installation directory and store it in a variable
          CREWAI_PATH=$(python -c "import crewai; print(crewai.__path__[0])")
          # Use the path in the PyInstaller command
          pyinstaller --add-data "$CREWAI_PATH;crewai" app.spec
          mv dist/GPT_Computer_Assistant.exe GPT_Computer_Assistant_windows.exe
        
      # Upload as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: GPT_Computer_Assistant_windows.exe

