name: Custom Package

on:
  workflow_dispatch: 


permissions:
  packages: write      


concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event }}
  cancel-in-progress: true
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          pyinstaller_ver: '==5.13.2'
          spec: 'app.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'windows'
          options: --onefile, --name "GPT_Computer_Assistant_windows", --windowed, 




  macos:
    runs-on: macos-latest
    steps:
      
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          pyinstaller_ver: '==5.13.2'
          spec: 'app.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'macos'
          options: --onefile, --name "GPT_Computer_Assistant_macos", --windowed, 
