name: Release Generator

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write      

jobs:


  release:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Getting Tag
        id: tag_extractor
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
    
      - uses: ncipollo/release-action@v1
        id: create_release
        with:
          name: GPT Computer Assistant ${{ steps.tag_extractor.outputs.latest_tag }}
          generateReleaseNotes: true
          tag: ${{ steps.tag_extractor.outputs.latest_tag }}



