name: "Test Publish"

on:

  workflow_dispatch:

jobs:
  run:
    name: "Build and publish test release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Run UV Sync
        run: |
          uv sync

      - name: Build
        run: uv build

      - name: Publish to TestPyPI
        run: uv publish --index testpypi -t ${{ secrets.TEST_THE_PYPI_TOKEN }} 
